global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: auth-service
    static_configs:
      - targets: ['auth-service:3001']
        labels:
          service: auth-service

  - job_name: academic-service
    static_configs:
      - targets: ['academic-service:3002']
        labels:
          service: academic-service

  - job_name: assignment-service
    static_configs:
      - targets: ['assignment-service:3003']
        labels:
          service: assignment-service
